# Google App Engine deployment configuration
runtime: python312
service: default

env_variables:
  STREAMLIT_SERVER_PORT: 8080
  STREAMLIT_SERVER_ADDRESS: 0.0.0.0
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: false
  STREAMLIT_SERVER_HEADLESS: true

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto
  secure: always