[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
maxUploadSize = 200
address = "0.0.0.0"
enableStaticServing = false
enableWebsocketCompression = false
baseUrlPath = "/"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[runner]
magicEnabled = false
installTracer = false
fixMatplotlib = true

[theme]
primaryColor = "#667eea"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
