[server]
headless = true
enableCORS = true
enableXsrfProtection = false
port = 8501
maxUploadSize = 200
address = "0.0.0.0"
enableStaticServing = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#667eea"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
